version: '3.7'
services:
    rentbuydev:
        build:
          context: .
          dockerfile: Dockerfile
        env_file: 
          - ./.dev.env 
        volumes:
            - .:/app
        network_mode: cbb_server_net
        container_name: rentbuydev
        deploy:
          resources:
            limits:
              cpus: "2"
              memory: "2g"
        expose:
            - '5173'