version: '3.3'
services:
    rentbuydev:
        build:
          context: .
          dockerfile: Dockerfile
        env_file: 
          - ./.dev.env 
        volumes:
            - .:/app
        network_mode: cbb_server_net
        container_name: rentbuydev
        expose:
            - '5173'