name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Copy files to the s3 website content bucket
      run:
        aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET}}